import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import logo1 from '../images/logo1.png'
import logo2 from '../images/logo2.png'

const Home: NextPage = () => {
  return (
<>
      <Head>
        <title> Agnieszka Jankowska </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

     
      <main className="panel">
       
       <Link href="/fizjoterapia"> 
       <section className="panel-div">
         <img src={logo1.src} alt="fizjoterapia"/>
       </section> 
       </Link>
       <Link href="/fotografia"> 
       <section className="panel-div">
       <img src={logo2.src} alt="fotografia"/>
       </section>
       </Link>
      </main>
     
      </>  
  )
}

export default Home
